import { describe, test, expect } from 'vitest';
import { victimSafeCondition, VictimSafeConditions } from '../RaceSolverBuilder';
import jpSkills from '../data/jp/skill_data.json';
import globalSkills from '../data/global/skill_data.json';

// Every term a debuff condition can use must be explicitly classified. This is the tripwire for a
// data refresh introducing a new term: an unclassified one fails here rather than silently
// evaluating against the victim (denylist failure) or widening the window (allowlist failure).
const CASTER_TERMS = new Set([
	'order', 'order_rate', 'running_style', 'change_order_onetime',
	'blocked_front_continuetime',
	'temptation_opponent_count_behind', 'temptation_opponent_count_infront',
]);
const OTHER_TARGETS = new Set([2, 4, 7, 9, 10, 11, 18, 19, 20, 21, 22, 23]);

function debuffAlternatives(skills: object): any[] {
	const out: any[] = [];
	for (const s of Object.values(skills as any)) {
		for (const a of (s as any).alternatives) {
			for (const e of a.effects) {
				if (e.type === 9 && e.modifier < 0 && OTHER_TARGETS.has(e.target)) {
					out.push(a);
					break;
				}
			}
		}
	}
	return out;
}

function debuffConditions(skills: object): string[] {
	return debuffAlternatives(skills).map((a) => a.condition);
}

describe('victimSafeCondition', () => {
	test('strips caster terms, keeps timing and course terms', () => {
		expect(victimSafeCondition('distance_type==3&phase==1&blocked_front_continuetime>=1'))
			.toBe('distance_type==3&phase==1');                       // Murmur
		expect(victimSafeCondition('running_style==3&phase_random==2&order_rate>50'))
			.toBe('phase_random==2');                                 // All-Seeing Eyes
		expect(victimSafeCondition('phase==1&order_rate<=50&temptation_opponent_count_behind>=1'))
			.toBe('phase==1');                                        // Trick (Front), unregistered term
		expect(victimSafeCondition('running_style_count_nige_otherself>=1&phase_random==0&accumulatetime>=5'))
			.toBe('running_style_count_nige_otherself>=1&phase_random==0&accumulatetime>=5'); // Subdued Front Runners: victim-safe, kept
	});

	test('filters each @-branch independently (& binds tighter than @)', () => {
		expect(victimSafeCondition('phase==1&order>=2@phase_random==2&running_style==3'))
			.toBe('phase==1@phase_random==2');
	});

	test('an emptied branch makes the whole condition unconditional', () => {
		expect(victimSafeCondition('order>=2')).toBe('');
		expect(victimSafeCondition('order>=2@phase==1')).toBe('');
	});

	// HP-7 review-3, Important 9: previously JP-only. The entire allowlist-over-denylist argument
	// (docs/adr/0014-victim-safe-debuff-conditions.md) rests on this tripwire catching an
	// unclassified term before it ships -- it did not cover what the Global build actually runs
	// on (uma-skill-tools/data/global/skill_data.json), generated by the same .pl scripts against
	// a different master.mdb and therefore capable of shipping a term JP's data never has.
	describe.each([
		['JP', jpSkills],
		['Global', globalSkills],
	])('%s dataset', (_name, skills) => {
		test('every term in every shipped debuff condition is explicitly classified', () => {
			const unclassified = new Set<string>();
			for (const c of debuffConditions(skills)) {
				for (const clause of c.split(/[&@]/)) {
					const term = clause.replace(/[<>=!].*/, '');
					if (!VictimSafeConditions.has(term) && !CASTER_TERMS.has(term)) unclassified.add(term);
				}
			}
			expect([...unclassified]).toEqual([]);
		});

		test('no shipped debuff condition strips to empty', () => {
			for (const c of debuffConditions(skills)) expect(victimSafeCondition(c)).not.toBe('');
		});

		// HP-7 review-9 housekeeping: victimSafeCondition() deliberately PRESERVES '@' (OR)
		// structure (see its own `branches.join('@')` above) -- but StaminaDebuffs.ts's three
		// parsers (parseWindow/parseDistanceType/parseStrategy) each split on /[&@]/ indiscriminately
		// and take the FIRST matching clause, silently dropping any other distinct value a real OR
		// would carry. Dormant today: debuffAlternatives() above filters on OTHER_TARGETS, and zero
		// of the resulting debuff-capable conditions (30 JP / 21 Global) strip to an '@'. The one
		// skill that WOULD (113001211: `phase_random==1&ground_type==1&slope==1@phase_random==1&
		// ground_type==1&slope==2`, stripping to `phase_random==1@phase_random==1`) is excluded only
		// because its effects are SkillTarget.Self, not one of OTHER_TARGETS -- and its two branches
		// happen to be identical, so a first-match parser would be accidentally correct on it anyway.
		// Do NOT broaden debuffAlternatives()'s target filter to "fix" this exclusion -- doing so
		// would make this assertion fail on 113001211.
		test('no shipped debuff condition strips to an OR', () => {
			for (const c of debuffConditions(skills)) expect(victimSafeCondition(c)).not.toContain('@');
		});

		// Peer-review fix (HP-7 review round 2, Important 5): ActivationConditions.ts's own comment
		// above these four entries warns "abusing valueFilter like this only works because these
		// conditions are used like running_style_count_nige_otherself>=1" -- each is implemented as a
		// bare valueFilter that only reads the comparison's truthiness, not its magnitude, so a future
		// data refresh shipping e.g. `>=2` on one of these terms would keep it classified (the
		// unclassified-term tripwire above stays green) but silently never fire (1 >= 2 is false for
		// every victim) -- precisely the invisible under-firing this file's own "Allowlist over
		// denylist" comment argues the allowlist protects against for every OTHER term. This asserts
		// the operator these four terms are shipped with, which the unclassified-term check alone
		// cannot: it strips the operator+value before checking term names.
		test('running_style_count_*_otherself terms are shipped only as >=1, never a different operator/value', () => {
			const STYLE_TERMS = [
				'running_style_count_nige_otherself',
				'running_style_count_senko_otherself',
				'running_style_count_sashi_otherself',
				'running_style_count_oikomi_otherself',
			];
			let matched = 0;
			for (const c of debuffConditions(skills)) {
				for (const clause of c.split(/[&@]/)) {
					const term = clause.replace(/[<>=!].*/, '');
					if (STYLE_TERMS.includes(term)) {
						matched++;
						expect(clause).toBe(`${term}>=1`);
					}
				}
			}
			expect(matched).toBeGreaterThan(0); // sanity: the shipped data still exercises this at all
		});

		// HP-7 review-3, Important 9: `.precondition` is not routed through victimSafeCondition at
		// all (only `.condition` is -- RaceSolverBuilder.ts's buildSkillData) -- latent, since no
		// shipped debuff has one, but with no tripwire and the ADR not even mentioning
		// preconditions. This fails loudly the moment a shipped debuff ever gains one, forcing that
		// gap to be addressed rather than silently evaluating a caster-shaped precondition against
		// the victim.
		test('no shipped debuff alternative carries a precondition', () => {
			for (const a of debuffAlternatives(skills)) {
				expect(a.precondition).toBeFalsy();
			}
		});
	});
});
